export const SET_USER_LATLONG = "SET_USER_LATLONG";
export const SET_USER_WOEID = "SET_USER_WOEID";
export const SET_CURRENT_WEATHER_ABBR = "SET_CURRENT_WEATHER_ABBR";
export const SET_CURRENT_DEGREES = "SET_CURRENT_DEGREES";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";
export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
